all:
  hosts:
    node1:
      ansible_host: 192.168.1.20
      ip: 192.168.1.20
      access_ip: 192.168.1.20
    node2:
      ansible_host: 192.168.1.21
      ip: 192.168.1.21
      access_ip: 192.168.1.21
    node3:
      ansible_host: 192.168.1.12
      ip: 192.168.1.12
      access_ip: 192.168.1.12
    node4:
      ansible_host: 192.168.1.13
      ip: 192.168.1.13
      access_ip: 192.168.1.13
    node5:
      ansible_host: 192.168.1.14
      ip: 192.168.1.14
      access_ip: 192.168.1.14
    node6:
      ansible_host: 192.168.1.11
      ip: 192.168.1.11
      access_ip: 192.168.1.11
    node7:
      ansible_host: 192.168.1.10
      ip: 192.168.1.10
      access_ip: 192.168.1.10
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node6:
        node7:
    etcd:
      hosts:
        node3:
        node4:
        node5:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
