all:
  hosts:
    node1:
      ansible_host: 192.168.1.24
      ip: 192.168.1.24
      access_ip: 192.168.1.24
    node2:
      ansible_host: 192.168.1.21
      ip: 192.168.1.21
      access_ip: 192.168.1.21
    node3:
      ansible_host: 192.168.1.12
      ip: 192.168.1.12
      access_ip: 192.168.1.12
    node4:
      ansible_host: 192.168.1.13
      ip: 192.168.1.13
      access_ip: 192.168.1.13
    node5:
      ansible_host: 192.168.1.14
      ip: 192.168.1.14
      access_ip: 192.168.1.14
    node6:
      ansible_host: 192.168.1.11
      ip: 192.168.1.11
      access_ip: 192.168.1.11
    node7:
      ansible_host: 192.168.1.10
      ip: 192.168.1.10
      access_ip: 192.168.1.10
    node8:
      ansible_host: 192.168.1.22
      ip: 192.168.1.22
      access_ip: 192.168.1.22
    node9:
      ansible_host: 192.168.1.23
      ip: 192.168.1.23
      access_ip: 192.168.1.23
    node10:
      ansible_host: 192.168.1.28
      ip: 192.168.1.28
      access_ip: 192.168.1.28
    node11:
      ansible_host: 192.168.1.29
      ip: 192.168.1.29
      access_ip: 192.168.1.29
    node12:
      ansible_host: 192.168.1.25
      ip: 192.168.1.25
      access_ip: 192.168.1.25
    node13:
      ansible_host: 192.168.1.30
      ip: 192.168.1.30
      access_ip: 192.168.1.30
    node14:
      ansible_host: 192.168.1.31
      ip: 192.168.1.31
      access_ip: 192.168.1.31
    node15:
      ansible_host: 192.168.1.32
      ip: 192.168.1.32
      access_ip: 192.168.1.32
  children:
    kube_control_plane:
      hosts:
        node1:
        node8:
    kube_node:
      hosts:
        node9:
        node10:
        node11:
    etcd:
      hosts:
        node12:
        node13:
        node14:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
